const lists = {
  fr_marche1: {
  title: "Frans - Marche1",
  words: [
    { taal: "zéro", nl: "0" },
    { taal: "un", nl: "1" },
    { taal: "deux", nl: "2" },
    { taal: "trois", nl: "3" },
    { taal: "quatre", nl: "4" },
    { taal: "cinq", nl: "5" },
    { taal: "six", nl: "6" },
    { taal: "sept", nl: "7" },
    { taal: "huit", nl: "8" },
    { taal: "neuf", nl: "9" },
    { taal: "dix", nl: "10" },
    { taal: "onze", nl: "11" },
    { taal: "douze", nl: "12" },
    { taal: "treize", nl: "13" },
    { taal: "quatorze", nl: "14" },
    { taal: "quinze", nl: "15" },
    { taal: "seize", nl: "16" },
    { taal: "dix-sept", nl: "17" },
    { taal: "dix-huit", nl: "18" },
    { taal: "dix-neuf", nl: "19" },
    { taal: "vingt", nl: "20" },
  ]
},
fr_marche1_fix: {
  title: "Frans - Marche1",
  words: [
    { taal: "je suis", nl: "ik ben" },
    { taal: "j'ai", nl: "ik heb" },
    { taal: "ne pas", nl: "niet" },
    { taal: "ne plus", nl: "niet meer" },
    { taal: "de", nl: "van" },
    { taal: "le", nl: "de (m) / het (m)" },
    { taal: "la", nl: "de (v) / het (v)" },
    { taal: "l’", nl: "de / het" },
    { taal: "les", nl: "de (mv)" },
    { taal: "un", nl: "een (m)" },
    { taal: "une", nl: "een (v)" },
    { taal: "que", nl: "dat / wat" },
    { taal: "ça", nl: "het / dat" },
    { taal: "et", nl: "en" },
    { taal: "à", nl: "in / naar" },
    { taal: "moi", nl: "ik / mij" },
    { taal: "mais", nl: "maar" },
    { taal: "pour", nl: "voor / om te" },
    { taal: "qui", nl: "wie" },
    { taal: "il y a", nl: "er is / er zijn" },
    { taal: "bien", nl: "goed" },
    { taal: "avec", nl: "met" },
    { taal: "si", nl: "als / of" },
    { taal: "j'aimerais", nl: "ik zou graag willen" },
  ]
},
  fr_marche2: {
  title: "Frans - Marche2",
  words: [
    { taal: "je", nl: "ik" },
    { taal: "tu", nl: "jij" },
    { taal: "il", nl: "hij" },
    { taal: "nous", nl: "wij" },
    { taal: "vous", nl: "jullie / u" },
    { taal: "ils / elles", nl: "zij (mv)" },
    { taal: "elle", nl: "zij" },
    { taal: "on", nl: "men" },
  ]
},
fr_marche2_fix: {
  title: "Frans - Marche2",
  words: [
    { taal: "je vais", nl: "ik ga" },
    { taal: "aller", nl: "gaan" },
    { taal: "je fais", nl: "ik maak / ik doe" },
    { taal: "faire", nl: "maken / doen" },
    { taal: "je peux", nl: "ik kan / ik mag" },
    { taal: "pouvoir", nl: "kunnen / mogen" },
    { taal: "je veux", nl: "ik wil" },
    { taal: "vouloir", nl: "willen" },
    { taal: "oui", nl: "ja" },
    { taal: "non", nl: "nee" },
    { taal: "toi", nl: "jij / jou" },
    { taal: "comme", nl: "als / zoals" },
    { taal: "ici", nl: "hier" },
    { taal: "chez", nl: "bij / naar" },
    { taal: "lui", nl: "hem / haar" },
    { taal: "là-bas", nl: "daar" },
    { taal: "ne…rien", nl: "niets" },
    { taal: "par", nl: "door" },
    { taal: "alors", nl: "dan" },
    { taal: "maintenant", nl: "nu" },
    { taal: "autre", nl: "andere" },
    { taal: "bon-bonne", nl: "goed / lekker" },
    { taal: "ou", nl: "of" },
    { taal: "très", nl: "erg" },
  ]
},

  fr_marche3: {
    title: "Frans - Marche3",
    words: [
      { taal: "devant", nl: "voor" },
      { taal: "derrière", nl: "achter" },
      { taal: "sur", nl: "op" },
      { taal: "sous", nl: "onder" },
      { taal: "dans", nl: "in" },
      { taal: "entre", nl: "tussen" },
      { taal: "à gauche de", nl: "links van" },
      { taal: "à droite de", nl: "rechts van" },
      { taal: "à côté de", nl: "naast" },
      { taal: "au-dessus de", nl: "boven" },
      { taal: "loin de", nl: "ver van" },
      { taal: "près de", nl: "dichtbij" },
    ]
  },
  fr_marche3_fix: {
  title: "Frans - Marche3",
  words: [
    { taal: "je viens", nl: "ik kom" },
    { taal: "je sais", nl: "ik weet" },
    { taal: "je vois", nl: "ik zie" },
    { taal: "merci", nl: "bedankt" },
    { taal: "même", nl: "dezelfde / zelfs" },
    { taal: "ne…jamais", nl: "nooit" },
    { taal: "aussi", nl: "ook" },
    { taal: "la chose", nl: "het ding" },
    { taal: "quelque chose", nl: "iets" },
    { taal: "tous", nl: "allemaal" },
    { taal: "il faut", nl: "je moet / je hebt nodig" },
    { taal: "encore", nl: "nog" },
    { taal: "un peu", nl: "een beetje" },
    { taal: "vraiment", nl: "echt" },
    { taal: "le temps", nl: "de tijd / het weer" },
    { taal: "la vie", nl: "het leven" },
    { taal: "quelques", nl: "enkele" },
    { taal: "sans", nl: "zonder" },
    { taal: "juste", nl: "juist / precies" },
    { taal: "toujours", nl: "altijd / nog steeds" },
    ]
  },
  fr_marche4: {
  title: "Frans - Marche4",
  words: [
    { taal: "le grand-père", nl: "de opa" },
    { taal: "la grand-mère", nl: "de oma" },
    { taal: "le père", nl: "de vader" },
    { taal: "la mère", nl: "de moeder" },
    { taal: "la soeur", nl: "de zus" },
    { taal: "le frère", nl: "de broer" },
    { taal: "l'oncle", nl: "de oom" },
    { taal: "la tante", nl: "de tante" },
    { taal: "le fils", nl: "de zoon" },
    { taal: "la fille", nl: "de dochter" },
    { taal: "le cousin", nl: "de neef" },
    { taal: "la cousine", nl: "de nicht" },
    { taal: "le neveu", nl: "de neef (van je oom of tante)" },
    { taal: "la nièce", nl: "de nicht (van je oom of tante)" },
    { taal: "le petit-fils", nl: "de kleinzoon" },
    { taal: "la petite-fille", nl: "de kleindochter" },
    { taal: "le petit ami", nl: "het vriendje" },
    { taal: "la petite amie", nl: "het vriendinnetje" },
    { taal: "le demi-frère", nl: "de halfbroer" },
    { taal: "la demi-soeur", nl: "de halfzus" },
    { taal: "le beau-frère", nl: "de stiefbroer" },
    { taal: "la belle-soeur", nl: "de stiefzus" },
    { taal: "les parents", nl: "de ouders" },
    ]
  },
   fr_marche4_fix: {
  title: "Frans - Marche4",
  words: [
    { taal: "je dois", nl: "ik moet" },
    { taal: "je crois", nl: "ik geloof" },
    { taal: "j'ai besoin de", nl: "ik heb nodig" },
    { taal: "j'ai mal", nl: "ik heb pijn" },
    { taal: "j'aime", nl: "ik houd van" },
    { taal: "tout", nl: "alles" },
    { taal: "d'accord", nl: "oké" },
    { taal: "le monde", nl: "de wereld" },
    { taal: "tout le monde", nl: "iedereen" },
    { taal: "la fois", nl: "de keer" },
    { taal: "trop", nl: "te" },
    { taal: "l'homme (M)", nl: "de man" },
    { taal: "la femme", nl: "de vrouw" },
    { taal: "monsieur", nl: "meneer" },
    { taal: "madame", nl: "mevrouw" },
    { taal: "le garçon", nl: "de jongen" },
    { taal: "la fille", nl: "het meisje / de dochter" },
    { taal: "c'est", nl: "het is" },
    { taal: "sûr", nl: "zeker" },
    { taal: "bien sûr", nl: "natuurlijk" },
  ]
},

  fr_marche5_fix: {
    title: "Frans - Marche 5 (Fix)",
    words: [
      { taal: "je dis", nl: "ik zeg" },
      { taal: "je regarde", nl: "ik kijk naar" },
      { taal: "je parle", nl: "ik praat / ik spreek" },
  
      { taal: "l'argent (M)", nl: "het geld" },
      { taal: "la maison", nl: "het huis" },
  
      { taal: "grand", nl: "groot" },
      { taal: "petit", nl: "klein" },
  
      { taal: "ne … personne", nl: "niemand" },
      { taal: "vrai", nl: "waar / echt" },
      { taal: "faux", nl: "niet waar / nep" },
  
      { taal: "donc", nl: "dus" },
      { taal: "avant", nl: "voor" },
      { taal: "depuis", nl: "sinds" },
      { taal: "parce que", nl: "omdat" },
      { taal: "beaucoup", nl: "veel" },
      { taal: "mieux", nl: "beter" },
      { taal: "après", nl: "na" },
  
      { taal: "bonjour", nl: "hallo" },
      { taal: "au revoir", nl: "tot ziens" },
      { taal: "salut", nl: "hoi / doei" },
    ]
  },
  fr_marche5: {
    title: "Frans - Marche 5",
    words: [
      { taal: "bleu", nl: "blauw" },
      { taal: "rouge", nl: "rood" },
      { taal: "jaune", nl: "geel" },
      { taal: "vert", nl: "groen" },
      { taal: "rose", nl: "roze" },
      { taal: "violet", nl: "paars" },
      { taal: "marron", nl: "bruin" },
      { taal: "beige", nl: "beige" },
      { taal: "orange", nl: "oranje" },
      { taal: "gris", nl: "grijs" },
      { taal: "noir", nl: "zwart" },
      { taal: "blanc-blanche", nl: "wit" },
  
      { taal: "la robe", nl: "de jurk" },
      { taal: "la jupe", nl: "de rok" },
      { taal: "le jean", nl: "de spijkerbroek" },
      { taal: "le short", nl: "de korte broek" },
      { taal: "la veste", nl: "het jack" },
      { taal: "le pull", nl: "de trui" },
      { taal: "le T-shirt", nl: "het T-shirt" },
      { taal: "la casquette", nl: "de pet" },
      { taal: "la chaussure", nl: "de schoen" },
      { taal: "la basket", nl: "de sneaker" },
      { taal: "la tong", nl: "de slipper" },
      { taal: "la botte", nl: "de laars" },
      { taal: "la chaussette", nl: "de sok" },
    ]
  },
  fr_marche6_fix: {
    title: "Frans - Marche 6 (Fix)",
    words: [
      { taal: "j'arrive", nl: "ik kom aan / ik kom eraan" },
      { taal: "j'appelle", nl: "ik roep" },
      { taal: "je reste", nl: "ik blijf" },
      { taal: "je pense", nl: "ik denk" },
      { taal: "j'ai raison", nl: "ik heb gelijk" },
      { taal: "j'ai peur de", nl: "ik ben bang voor" },
  
      { taal: "le matin", nl: "de ochtend" },
      { taal: "le jour", nl: "de dag" },
      { taal: "le soir", nl: "de avond" },
      { taal: "la nuit", nl: "de nacht" },
      { taal: "les gens", nl: "de mensen" },
      { taal: "l'enfant", nl: "het kind" },
  
      { taal: "déjà", nl: "al" },
      { taal: "voilà", nl: "alstublieft / hier is" },
      { taal: "ce", nl: "deze (m) / dit (m)" },
      { taal: "cette", nl: "deze (v) / dit (v)" },
      { taal: "ces", nl: "deze (mv)" },
  
      { taal: "désolé", nl: "sorry / helaas" },
      { taal: "moins", nl: "minder" },
      { taal: "seul", nl: "alleen" },
      { taal: "vite", nl: "snel" },
      { taal: "puis", nl: "daarna" },
    ]
  },
  fr_marche6: {
    title: "Frans - Marche 6",
    words: [
      { taal: "dix", nl: "10" },
      { taal: "vingt", nl: "20" },
      { taal: "trente", nl: "30" },
      { taal: "quarante", nl: "40" },
      { taal: "cinquante", nl: "50" },
      { taal: "soixante", nl: "60" },
      { taal: "soixante-cinq", nl: "65" },
      { taal: "soixante-dix", nl: "70" },
      { taal: "soixante-quinze", nl: "75" },
      { taal: "quatre-vingts", nl: "80" },
      { taal: "quatre-vingt-trois", nl: "83" },
      { taal: "quatre-vingt-dix", nl: "90" },
      { taal: "quatre-vingt-treize", nl: "93" },
      { taal: "cent", nl: "100" },
      { taal: "deux cents", nl: "200" },
      { taal: "mille", nl: "1000" },
      { taal: "million", nl: "1000000" },
    ]
  },
  fr_marche7_fix: {
    title: "Frans - Marche 7 (Fix)",
    words: [
      { taal: "je prends", nl: "ik neem" },
      { taal: "je comprends", nl: "ik begrijp" },
      { taal: "plaire", nl: "bevallen" },
      { taal: "j'attends", nl: "ik wacht op" },
      { taal: "je passe", nl: "ik breng door" },
      { taal: "j'arrête", nl: "ik stop" },
      { taal: "j'aide", nl: "ik help" },
  
      { taal: "l'air (M)", nl: "de lucht" },
      { taal: "l'amour (M)", nl: "de liefde" },
      { taal: "le problème", nl: "het probleem" },
      { taal: "la chance", nl: "het succes" },
      { taal: "l'attention (F)", nl: "attentie / aandacht" },
  
      { taal: "hier", nl: "gisteren" },
      { taal: "aujourd’hui", nl: "vandaag" },
      { taal: "demain", nl: "morgen" },
      { taal: "en", nl: "in / naar" },
  
      { taal: "haut", nl: "hoog" },
      { taal: "bas-basse", nl: "laag" },
      { taal: "assez", nl: "genoeg / nogal" },
      { taal: "ni … ni", nl: "niet … ook niet" },
    ]
  },
  fr_marche7: {
    title: "Frans - Marche 7",
    words: [
      { taal: "lundi", nl: "maandag" },
      { taal: "mardi", nl: "dinsdag" },
      { taal: "mercredi", nl: "woensdag" },
      { taal: "jeudi", nl: "donderdag" },
      { taal: "vendredi", nl: "vrijdag" },
      { taal: "samedi", nl: "zaterdag" },
      { taal: "dimanche", nl: "zondag" },
  
      { taal: "janvier", nl: "januari" },
      { taal: "février", nl: "februari" },
      { taal: "mars", nl: "maart" },
      { taal: "avril", nl: "april" },
      { taal: "mai", nl: "mei" },
      { taal: "juin", nl: "juni" },
      { taal: "juillet", nl: "juli" },
      { taal: "août", nl: "augustus" },
      { taal: "septembre", nl: "september" },
      { taal: "octobre", nl: "oktober" },
      { taal: "novembre", nl: "november" },
      { taal: "décembre", nl: "december" },
  
      { taal: "l'hiver (M)", nl: "de winter" },
      { taal: "le printemps", nl: "de lente" },
      { taal: "l'été (M)", nl: "de zomer" },
      { taal: "l'automne (M)", nl: "de herfst" },
    ]
  },
  fr_marche8_fix: {
    title: "Frans - Marche 8 (Fix)",
    words: [
      { taal: "je connais", nl: "ik ken" },
      { taal: "je pars", nl: "ik vertrek" },
      { taal: "je revois", nl: "ik zie weer" },
      { taal: "j'apprends", nl: "ik leer" },
  
      { taal: "le moment", nl: "het moment" },
      { taal: "la seconde", nl: "de seconde" },
      { taal: "la minute", nl: "de minuut" },
      { taal: "l'heure (F)", nl: "het uur" },
  
      { taal: "tôt", nl: "vroeg" },
      { taal: "tard", nl: "laat" },
  
      { taal: "l'ami (M)", nl: "de vriend" },
      { taal: "l'amie (F)", nl: "de vriendin" },
      { taal: "le corps", nl: "het lichaam" },
      { taal: "la main", nl: "de hand" },
      { taal: "la tête", nl: "het hoofd" },
      { taal: "les yeux", nl: "de ogen" },
  
      { taal: "tant de", nl: "zoveel" },
      { taal: "pendant", nl: "tijdens" },
      { taal: "vieux / vieille", nl: "oud" },
      { taal: "nouveau / nouvelle", nl: "nieuw" },
    ]
  },
  fr_marche8: {
    title: "Frans - Marche 8",
    words: [
      { taal: "qui", nl: "wie" },
      { taal: "que / qu’est-ce que", nl: "wat" },
      { taal: "quoi", nl: "wat" },
      { taal: "comment", nl: "hoe" },
      { taal: "combien", nl: "hoeveel" },
      { taal: "où", nl: "waar" },
      { taal: "pourquoi", nl: "waarom" },
      { taal: "quand", nl: "wanneer" },
      { taal: "quel / quelle", nl: "welk / welke" },
    ]
  },
  fr_marche9_fix: {
    title: "Frans - Marche 9 (Fix)",
    words: [
      { taal: "je sens", nl: "ik ruik / ik voel" },
      { taal: "j'entends", nl: "ik hoor" },
      { taal: "je cherche", nl: "ik zoek" },
      { taal: "je demande", nl: "ik vraag" },
      { taal: "je trouve", nl: "ik vind" },
      { taal: "j'utilise", nl: "ik gebruik" },
      { taal: "je travaille", nl: "ik werk" },
  
      { taal: "le travail", nl: "het werk" },
      { taal: "la voiture", nl: "de auto" },
      { taal: "le sens", nl: "de betekenis" },
      { taal: "la part", nl: "het deel" },
      { taal: "la porte", nl: "de deur" },
      { taal: "le coup", nl: "de klap" },
      { taal: "les lunettes", nl: "de bril" },
      { taal: "le portable", nl: "het mobieltje" },
      { taal: "le collier", nl: "de ketting" },
  
      { taal: "chaque", nl: "elke" },
      { taal: "ensemble", nl: "samen" },
      { taal: "moche", nl: "lelijk" },
      { taal: "beau / belle", nl: "mooi" },
    ]
  },
    fr_marche9: {
    title: "Frans - Marche 9",
    words: [
      { taal: "mon / ma / mes", nl: "mijn" },
      { taal: "ton / ta / tes", nl: "jouw" },
      { taal: "son / sa / ses", nl: "zijn / haar" },
      { taal: "notre / notre / nos", nl: "ons / onze" },
      { taal: "votre / votre / vos", nl: "jullie / uw" },
      { taal: "leur / leur / leurs", nl: "hun" },
    ]
  },
  fr_marche10_fix: {
    title: "Frans - Marche 10 (Fix)",
    words: [
      { taal: "je sors", nl: "ik ga uit" },
      { taal: "je tiens", nl: "ik hou vast" },
      { taal: "je finis", nl: "ik eindig / ik maak af" },
      { taal: "je mets", nl: "ik zet" },
      { taal: "je donne", nl: "ik geef" },
  
      { taal: "le sang", nl: "het bloed" },
      { taal: "la question", nl: "de vraag" },
      { taal: "l'histoire (F)", nl: "het verhaal / de geschiedenis" },
      { taal: "le jour", nl: "de dag" },
      { taal: "le calendrier", nl: "de kalender" },
      { taal: "le mois", nl: "de maand" },
      { taal: "l'année", nl: "het jaar" },
  
      { taal: "dehors", nl: "buiten" },
      { taal: "fou-folle", nl: "gek" },
      { taal: "la vérité", nl: "de waarheid" },
      { taal: "le tour", nl: "de ronde" },
      { taal: "la tour", nl: "de toren" },
      { taal: "plutôt", nl: "liever" },
      { taal: "meilleur", nl: "beter" },
      { taal: "presque", nl: "bijna" },
    ]
  },
    fr_marche10: {
  title: "Frans - Marche 10",
  words: [
    { taal: "le chien", nl: "de hond" },
    { taal: "le chat", nl: "de kat" },
    { taal: "le lapin", nl: "het konijn" },
    { taal: "l'oiseau (M)", nl: "de vogel" },
    { taal: "le papillon", nl: "de vlinder" },
    { taal: "le poisson", nl: "de vis" },
    { taal: "la tortue", nl: "de schildpad" },
    { taal: "la vache", nl: "de koe" },
    { taal: "le cheval", nl: "het paard" },
    { taal: "le mouton", nl: "het schaap" },
    { taal: "le cochon", nl: "het varken" },
    { taal: "la chèvre", nl: "de geit" },
    { taal: "le coq", nl: "de haan" },
    { taal: "la poule", nl: "de kip" },
    { taal: "l'hippopotame (M)", nl: "het nijlpaard" },
    { taal: "le rhinocéros", nl: "de neushoorn" },
    { taal: "la girafe", nl: "de giraf" },
    { taal: "le lion", nl: "de leeuw" },
    { taal: "le tigre", nl: "de tijger" },
    { taal: "l'éléphant", nl: "de olifant" },
    { taal: "le zèbre", nl: "de zebra" },
    { taal: "le crocodile", nl: "de krokodil" },
    { taal: "le serpent", nl: "de slang" },
    { taal: "la lionne", nl: "de leeuwin" },
  ]
},
fr_marche11_fix: {
  title: "Frans - Marche 11 (Fix)",
  words: [
    { taal: "je perds", nl: "ik verlies" },
    { taal: "je laisse", nl: "ik laat" },
    { taal: "je marche", nl: "ik loop" },
    { taal: "je joue", nl: "ik speel" },
    { taal: "j'écoute", nl: "ik luister" },

    { taal: "la ville", nl: "de stad" },
    { taal: "l'eau (F)", nl: "het water" },
    { taal: "le cas", nl: "het geval" },
    { taal: "la police", nl: "de politie" },
    { taal: "la terre", nl: "de aarde" },
    { taal: "la place", nl: "de plaats / het plein" },
    { taal: "le car", nl: "de bus" },

    { taal: "longtemps", nl: "lange tijd" },
    { taal: "contre", nl: "tegen" },
    { taal: "super", nl: "super" },
    { taal: "voici", nl: "hier is / hier zijn" },
    { taal: "vers", nl: "naar" },
    { taal: "seulement", nl: "alleen maar" },
    { taal: "eux", nl: "hen" },
    { taal: "car", nl: "want" },
  ]
},
fr_marche11: {
  title: "Frans - Marche 11",
  words: [
    { taal: "le football", nl: "voetbal" },
    { taal: "le basket-ball", nl: "basketbal" },
    { taal: "le volley-ball", nl: "volleybal" },
    { taal: "le hand-ball", nl: "handbal" },
    { taal: "le tennis", nl: "tennis" },
    { taal: "le hockey", nl: "hockey" },
    { taal: "le golf", nl: "golf" },
    { taal: "l'équitation (F)", nl: "paardrijden" },
    { taal: "la gymnastique", nl: "turnen" },
    { taal: "le ski", nl: "skiën" },
    { taal: "la natation", nl: "zwemmen" },
    { taal: "l'athlétisme (M)", nl: "atletiek" },
    { taal: "le cyclisme", nl: "wielrennen" },
    { taal: "la formule 1", nl: "formule 1" },
  ]
},
fr_avoir: {
  title: "Frans - Avoir",
  words: [
    { taal: "j'ai", nl: "ik heb" },
    { taal: "tu as", nl: "jij hebt" },
    { taal: "il a", nl: "hij heeft" },
    { taal: "elle a", nl: "zij heeft" },
    { taal: "nous avons", nl: "wij hebben" },
    { taal: "vous avez", nl: "jullie hebben / u heeft" },
    { taal: "ils ont", nl: "zij hebben" },
    { taal: "elles ont", nl: "zij hebben" },
  ]
},
fr_etre: {
  title: "Frans - Être",
  words: [
    { taal: "je suis", nl: "ik ben" },
    { taal: "tu es", nl: "jij bent" },
    { taal: "il est", nl: "hij is" },
    { taal: "elle est", nl: "zij is" },
    { taal: "nous sommes", nl: "wij zijn" },
    { taal: "vous êtes", nl: "jullie zijn / u bent" },
    { taal: "ils sont", nl: "zij zijn" },
    { taal: "elles sont", nl: "zij zijn" },
  ]
},
fr_er: {
  title: "Frans - Regelmatige -ER Werkwoorden",
  words: [
    { taal: "-e", nl: "je" },
    { taal: "-es", nl: "tu" },
    { taal: "-e", nl: "il / elle" },
    { taal: "-ons", nl: "nous" },
    { taal: "-ez", nl: "vous" },
    { taal: "-ent", nl: "ils / elles" },
  ]
},
fr_aller: {
  title: "Frans - Aller",
  words: [
    { taal: "je vais", nl: "ik ga" },
    { taal: "tu vas", nl: "jij gaat" },
    { taal: "il va", nl: "hij gaat" },
    { taal: "elle va", nl: "zij gaat" },
    { taal: "nous allons", nl: "wij gaan" },
    { taal: "vous allez", nl: "jullie gaan / u gaat" },
    { taal: "ils vont", nl: "zij gaan" },
    { taal: "elles vont", nl: "zij gaan" },
  ]
},
fr_faire: {
  title: "Frans - Faire",
  words: [
    { taal: "je fais", nl: "ik doe / maak" },
    { taal: "tu fais", nl: "jij doet / maakt" },
    { taal: "il fait", nl: "hij doet / maakt" },
    { taal: "elle fait", nl: "zij doet / maakt" },
    { taal: "nous faisons", nl: "wij doen / maken" },
    { taal: "vous faites", nl: "jullie doen / maken" },
    { taal: "ils font", nl: "zij doen / maken" },
    { taal: "elles font", nl: "zij doen / maken" },
  ]
},
eng_verbs: {
  title: "Frans - Verbs",
  words: [
    { taal: "zijn/worden (Infinitive)", nl: "to be" },
    { taal: "zijn/worden (Past Simple)", nl: "was/were" },
    { taal: "zijn/worden (Past Participle)", nl: "been" },
    { taal: "slaan/kloppen (Infinitive)", nl: "to beat" },
    { taal: "slaan/kloppen (Past Simple)", nl: "beat" },
    { taal: "slaan/kloppen (Past Participle)", nl: "beaten" },
    { taal: "worden (Infinitive)", nl: "to become" },
    { taal: "worden (Past Simple)", nl: "became" },
    { taal: "worden (Past Participle)", nl: "become" },
    { taal: "beginnen (Infinitive)", nl: "to begin" },
    { taal: "beginnen (Past Simple)", nl: "began" },
    { taal: "beginnen (Past Participle)", nl: "begun" },
    { taal: "buigen (Infinitive)", nl: "to bend" },
    { taal: "buigen (Past Simple)", nl: "bent" },
    { taal: "buigen (Past Participle)", nl: "bent" },
    { taal: "wedden (Infinitive)", nl: "to bet" },
    { taal: "wedden (Past Simple)", nl: "bet" },
    { taal: "wedden (Past Participle)", nl: "bet" },
    { taal: "bijten (Infinitive)", nl: "to bite" },
    { taal: "bijten (Past Simple)", nl: "bit" },
    { taal: "bijten (Past Participle)", nl: "bitten" },
    { taal: "blazen/waaien (Infinitive)", nl: "to blow" },
    { taal: "blazen/waaien (Past Simple)", nl: "blew" },
    { taal: "blazen/waaien (Past Participle)", nl: "blown" },
    { taal: "breken (Infinitive)", nl: "to break" },
    { taal: "breken (Past Simple)", nl: "broke" },
    { taal: "breken (Past Participle)", nl: "broken" },
    { taal: "(mee)brengen (Infinitive)", nl: "to bring" },
    { taal: "(mee)brengen (Past Simple)", nl: "brought" },
    { taal: "(mee)brengen (Past Participle)", nl: "brought" },
    { taal: "bouwen (Infinitive)", nl: "to build" },
    { taal: "bouwen (Past Simple)", nl: "built" },
    { taal: "bouwen (Past Participle)", nl: "built" },
    { taal: "branden (Infinitive)", nl: "to burn" },
    { taal: "branden (Past Simple)", nl: "burnt" },
    { taal: "branden (Past Participle)", nl: "burnt" },
    { taal: "kopen (Infinitive)", nl: "to buy" },
    { taal: "kopen (Past Simple)", nl: "bought" },
    { taal: "kopen (Past Participle)", nl: "bought" },
    { taal: "vangen (Infinitive)", nl: "to catch" },
    { taal: "vangen (Past Simple)", nl: "caught" },
    { taal: "vangen (Past Participle)", nl: "caught" },
    { taal: "kiezen (Infinitive)", nl: "to choose" },
    { taal: "kiezen (Past Simple)", nl: "chose" },
    { taal: "kiezen (Past Participle)", nl: "chosen" },
    { taal: "komen (Infinitive)", nl: "to come" },
    { taal: "komen (Past Simple)", nl: "came" },
    { taal: "komen (Past Participle)", nl: "come" },
    { taal: "kosten (Infinitive)", nl: "to cost" },
    { taal: "kosten (Past Simple)", nl: "cost" },
    { taal: "kosten (Past Participle)", nl: "cost" },
    { taal: "snijden/knippen (Infinitive)", nl: "to cut" },
    { taal: "snijden/knippen (Past Simple)", nl: "cut" },
    { taal: "snijden/knippen (Past Participle)", nl: "cut" },
    { taal: "uitdelen/handelen (Infinitive)", nl: "to deal" },
    { taal: "uitdelen/handelen (Past Simple)", nl: "dealt" },
    { taal: "uitdelen/handelen (Past Participle)", nl: "dealt" },
    { taal: "graven (Infinitive)", nl: "to dig" },
    { taal: "graven (Past Simple)", nl: "dug" },
    { taal: "graven (Past Participle)", nl: "dug" },
    { taal: "doen (Infinitive)", nl: "to do" },
    { taal: "doen (Past Simple)", nl: "did" },
    { taal: "doen (Past Participle)", nl: "done" },
    { taal: "trekken/tekenen (Infinitive)", nl: "to draw" },
    { taal: "trekken/tekenen (Past Simple)", nl: "drew" },
    { taal: "trekken/tekenen (Past Participle)", nl: "drawn" },
    { taal: "dromen (Infinitive)", nl: "to dream" },
    { taal: "dromen (Past Simple)", nl: "dreamt" },
    { taal: "dromen (Past Participle)", nl: "dreamt" },
    { taal: "drinken (Infinitive)", nl: "to drink" },
    { taal: "drinken (Past Simple)", nl: "drank" },
    { taal: "drinken (Past Participle)", nl: "drunk" },
    { taal: "rijden/besturen (Infinitive)", nl: "to drive" },
    { taal: "rijden/besturen (Past Simple)", nl: "drove" },
    { taal: "rijden/besturen (Past Participle)", nl: "driven" },
    { taal: "eten (Infinitive)", nl: "to eat" },
    { taal: "eten (Past Simple)", nl: "ate" },
    { taal: "eten (Past Participle)", nl: "eaten" },
    { taal: "vallen (Infinitive)", nl: "to fall" },
    { taal: "vallen (Past Simple)", nl: "fell" },
    { taal: "vallen (Past Participle)", nl: "fallen" },
    { taal: "voeden (Infinitive)", nl: "to feed" },
    { taal: "voeden (Past Simple)", nl: "fed" },
    { taal: "voeden (Past Participle)", nl: "fed" },
    { taal: "voelen (Infinitive)", nl: "to feel" },
    { taal: "voelen (Past Simple)", nl: "felt" },
    { taal: "voelen (Past Participle)", nl: "felt" },
    { taal: "vechten (Infinitive)", nl: "to fight" },
    { taal: "vechten (Past Simple)", nl: "fought" },
    { taal: "vechten (Past Participle)", nl: "fought" },
    { taal: "vinden (Infinitive)", nl: "to find" },
    { taal: "vinden (Past Simple)", nl: "found" },
    { taal: "vinden (Past Participle)", nl: "found" },
    { taal: "vliegen (Infinitive)", nl: "to fly" },
    { taal: "vliegen (Past Simple)", nl: "flew" },
    { taal: "vliegen (Past Participle)", nl: "flown" },
    { taal: "vergeten (Infinitive)", nl: "to forget" },
    { taal: "vergeten (Past Simple)", nl: "forgot" },
    { taal: "vergeten (Past Participle)", nl: "forgotten" },
    { taal: "vergeven (Infinitive)", nl: "to forgive" },
    { taal: "vergeven (Past Simple)", nl: "forgave" },
    { taal: "vergeven (Past Participle)", nl: "forgiven" },
    { taal: "(be)vriezen (Infinitive)", nl: "to freeze" },
    { taal: "(be)vriezen (Past Simple)", nl: "froze" },
    { taal: "(be)vriezen (Past Participle)", nl: "frozen" },
    { taal: "(ver)krijgen (Infinitive)", nl: "to get" },
    { taal: "(ver)krijgen (Past Simple)", nl: "got" },
    { taal: "(ver)krijgen (Past Participle)", nl: "got" },
    { taal: "geven (Infinitive)", nl: "to give" },
    { taal: "geven (Past Simple)", nl: "gave" },
    { taal: "geven (Past Participle)", nl: "given" },
    { taal: "gaan (Infinitive)", nl: "to go" },
    { taal: "gaan (Past Simple)", nl: "went" },
    { taal: "gaan (Past Participle)", nl: "gone" },
    { taal: "groeien (Infinitive)", nl: "to grow" },
    { taal: "groeien (Past Simple)", nl: "grew" },
    { taal: "groeien (Past Participle)", nl: "grown" },
    { taal: "hangen (Infinitive)", nl: "to hang" },
    { taal: "hangen (Past Simple)", nl: "hung" },
    { taal: "hangen (Past Participle)", nl: "hung" },
    { taal: "hebben (Infinitive)", nl: "to have" },
    { taal: "hebben (Past Simple)", nl: "had" },
    { taal: "hebben (Past Participle)", nl: "had" },
    { taal: "horen (Infinitive)", nl: "to hear" },
    { taal: "horen (Past Simple)", nl: "heard" },
    { taal: "horen (Past Participle)", nl: "heard" },
    { taal: "verbergen (Infinitive)", nl: "to hide" },
    { taal: "verbergen (Past Simple)", nl: "hid" },
    { taal: "verbergen (Past Participle)", nl: "hidden" },
    { taal: "raken/slaan (Infinitive)", nl: "to hit" },
    { taal: "raken/slaan (Past Simple)", nl: "hit" },
    { taal: "raken/slaan (Past Participle)", nl: "hit" },
    { taal: "(vast)houden (Infinitive)", nl: "to hold" },
    { taal: "(vast)houden (Past Simple)", nl: "held" },
    { taal: "(vast)houden (Past Participle)", nl: "held" },
    { taal: "pijn doen (Infinitive)", nl: "to hurt" },
    { taal: "pijn doen (Past Simple)", nl: "hurt" },
    { taal: "pijn doen (Past Participle)", nl: "hurt" },
    { taal: "houden (Infinitive)", nl: "to keep" },
    { taal: "houden (Past Simple)", nl: "kept" },
    { taal: "houden (Past Participle)", nl: "kept" },
    { taal: "weten (Infinitive)", nl: "to know" },
    { taal: "weten (Past Simple)", nl: "knew" },
    { taal: "weten (Past Participle)", nl: "known" },
    { taal: "leggen/tafel dekken (Infinitive)", nl: "to lay" },
    { taal: "leggen/tafel dekken (Past Simple)", nl: "laid" },
    { taal: "leggen/tafel dekken (Past Participle)", nl: "laid" },
    { taal: "leiden (Infinitive)", nl: "to lead" },
    { taal: "leiden (Past Simple)", nl: "led" },
    { taal: "leiden (Past Participle)", nl: "led" },
    { taal: "leren (infinitive)", nl: "to learn" },
    { taal: "leren (past simple)", nl: "learnt" },
    { taal: "leren (past participle)", nl: "learnt" },
    { taal: "vertrekken/verlaten (infinitive)", nl: "to leave" },
    { taal: "vertrekken/verlaten (past simple)", nl: "left" },
    { taal: "vertrekken/verlaten (past participle)", nl: "left" },
    { taal: "(uit)lenen (infinitive)", nl: "to lend" },
    { taal: "(uit)lenen (past simple)", nl: "lent" },
    { taal: "(uit)lenen (past participle)", nl: "lent" },
    { taal: "laten (infinitive)", nl: "to let" },
    { taal: "laten (past simple)", nl: "let" },
    { taal: "laten (past participle)", nl: "let" },
    { taal: "liggen (infinitive)", nl: "to lie" },
    { taal: "liggen (past simple)", nl: "lay" },
    { taal: "liggen (past participle)", nl: "lain" },
    { taal: "aansteken/lichten (infinitive)", nl: "to light" },
    { taal: "aansteken/lichten (past simple)", nl: "lit" },
    { taal: "aansteken/lichten (past participle)", nl: "lit" },
    { taal: "verliezen (infinitive)", nl: "to lose" },
    { taal: "verliezen (past simple)", nl: "lost" },
    { taal: "verliezen (past participle)", nl: "lost" },
    { taal: "maken (infinitive)", nl: "to make" },
    { taal: "maken (past simple)", nl: "made" },
    { taal: "maken (past participle)", nl: "made" },
    { taal: "bedoelen/menen (infinitive)", nl: "to mean" },
    { taal: "bedoelen/menen (past simple)", nl: "meant" },
    { taal: "bedoelen/menen (past participle)", nl: "meant" },
    { taal: "ontmoeten (infinitive)", nl: "to meet" },
    { taal: "ontmoeten (past simple)", nl: "met" },
    { taal: "ontmoeten (past participle)", nl: "met" },
    { taal: "betalen (infinitive)", nl: "to pay" },
    { taal: "betalen (past simple)", nl: "paid" },
    { taal: "betalen (past participle)", nl: "paid" },
    { taal: "zetten/leggen (infinitive)", nl: "to put" },
    { taal: "zetten/leggen (past simple)", nl: "put" },
    { taal: "zetten/leggen (past participle)", nl: "put" },
    { taal: "lezen (infinitive)", nl: "to read /i:/" },
    { taal: "lezen (past simple)", nl: "read /e/" },
    { taal: "lezen (past participle)", nl: "read /e/" },
    { taal: "rijden (infinitive)", nl: "to ride" },
    { taal: "rijden (past simple)", nl: "rode" },
    { taal: "rijden (past participle)", nl: "ridden" },
    { taal: "luiden/bellen (infinitive)", nl: "to ring" },
    { taal: "luiden/bellen (past simple)", nl: "rang" },
    { taal: "luiden/bellen (past participle)", nl: "rung" },
    { taal: "rennen (infinitive)", nl: "to run" },
    { taal: "rennen (past simple)", nl: "ran" },
    { taal: "rennen (past participle)", nl: "run" },
    { taal: "zeggen (infinitive)", nl: "to say" },
    { taal: "zeggen (past simple)", nl: "said" },
    { taal: "zeggen (past participle)", nl: "said" },
    { taal: "zien (infinitive)", nl: "to see" },
    { taal: "zien (past simple)", nl: "saw" },
    { taal: "zien (past participle)", nl: "seen" },
    { taal: "verkopen (infinitive)", nl: "to sell" },
    { taal: "verkopen (past simple)", nl: "sold" },
    { taal: "verkopen (past participle)", nl: "sold" },
    { taal: "(ver)sturen (infinitive)", nl: "to send" },
    { taal: "(ver)sturen (past simple)", nl: "sent" },
    { taal: "(ver)sturen (past participle)", nl: "sent" },
    { taal: "zetten/stellen (infinitive)", nl: "to set" },
    { taal: "zetten/stellen (past simple)", nl: "set" },
    { taal: "zetten/stellen (past participle)", nl: "set" },
    { taal: "schudden (infinitive)", nl: "to shake" },
    { taal: "schudden (past simple)", nl: "shook" },
    { taal: "schudden (past participle)", nl: "shaken" },
    { taal: "schijnen/stralen (infinitive)", nl: "to shine" },
    { taal: "schijnen/stralen (past simple)", nl: "shone" },
    { taal: "schijnen/stralen (past participle)", nl: "shone" },
    { taal: "laten zien (infinitive)", nl: "to show" },
    { taal: "laten zien (past simple)", nl: "showed" },
    { taal: "laten zien (past participle)", nl: "shown" },
    { taal: "sluiten/dichtdoen (infinitive)", nl: "to shut" },
    { taal: "sluiten/dichtdoen (past simple)", nl: "shut" },
    { taal: "sluiten/dichtdoen (past participle)", nl: "shut" },
    { taal: "zingen (infinitive)", nl: "to sing" },
    { taal: "zingen (past simple)", nl: "sang" },
    { taal: "zingen (past participle)", nl: "sung" },
    { taal: "zitten (infinitive)", nl: "to sit" },
    { taal: "zitten (past simple)", nl: "sat" },
    { taal: "zitten (past participle)", nl: "sat" },
    { taal: "slapen (infinitive)", nl: "to sleep" },
    { taal: "slapen (past simple)", nl: "slept" },
    { taal: "slapen (past participle)", nl: "slept" },
    { taal: "ruiken (infinitive)", nl: "to smell" },
    { taal: "ruiken (past simple)", nl: "smelt" },
    { taal: "ruiken (past participle)", nl: "smelt" },
    { taal: "spreken (infinitive)", nl: "to speak" },
    { taal: "spreken (past simple)", nl: "spoke" },
    { taal: "spreken (past participle)", nl: "spoken" },
    { taal: "doorbrengen/besteden (infinitive)", nl: "to spend" },
    { taal: "doorbrengen/besteden (past simple)", nl: "spent" },
    { taal: "doorbrengen/besteden (past participle)", nl: "spent" },
    { taal: "morsen (infinitive)", nl: "to spill" },
    { taal: "morsen (past simple)", nl: "spilt" },
    { taal: "morsen (past participle)", nl: "spilt" },
    { taal: "spugen (infinitive)", nl: "to spit" },
    { taal: "spugen (past simple)", nl: "spat" },
    { taal: "spugen (past participle)", nl: "spat" },
    { taal: "staan (infinitive)", nl: "to stand" },
    { taal: "staan (past simple)", nl: "stood" },
    { taal: "staan (past participle)", nl: "stood" },
    { taal: "stelen (infinitive)", nl: "to steal" },
    { taal: "stelen (past simple)", nl: "stole" },
    { taal: "stelen (past participle)", nl: "stolen" },
    { taal: "steken/prikken (infinitive)", nl: "to sting" },
    { taal: "steken/prikken (past simple)", nl: "stung" },
    { taal: "steken/prikken (past participle)", nl: "stung" },
    { taal: "zinken (infinitive)", nl: "to sink" },
    { taal: "zinken (past simple)", nl: "sank" },
    { taal: "zinken (past participle)", nl: "sunk" },
    { taal: "slaan/staken/opvallen (infinitive)", nl: "to strike" },
    { taal: "slaan/staken/opvallen (past simple)", nl: "struck" },
    { taal: "slaan/staken/opvallen (past participle)", nl: "struck" },
    { taal: "zwemmen (infinitive)", nl: "to swim" },
    { taal: "zwemmen (past simple)", nl: "swam" },
    { taal: "zwemmen (past participle)", nl: "swum" },
    { taal: "nemen (infinitive)", nl: "to take" },
    { taal: "nemen (past simple)", nl: "took" },
    { taal: "nemen (past participle)", nl: "taken" },
    { taal: "leren/onderwijzen (infinitive)", nl: "to teach" },
    { taal: "leren/onderwijzen (past simple)", nl: "taught" },
    { taal: "leren/onderwijzen (past participle)", nl: "taught" },
    { taal: "scheuren (infinitive)", nl: "to tear" },
    { taal: "scheuren (past simple)", nl: "tore" },
    { taal: "scheuren (past participle)", nl: "torn" },
    { taal: "vertellen (infinitive)", nl: "to tell" },
    { taal: "vertellen (past simple)", nl: "told" },
    { taal: "vertellen (past participle)", nl: "told" },
    { taal: "denken (infinitive)", nl: "to think" },
    { taal: "denken (past simple)", nl: "thought" },
    { taal: "denken (past participle)", nl: "thought" },
    { taal: "werpen/gooien (infinitive)", nl: "to throw" },
    { taal: "werpen/gooien (past simple)", nl: "threw" },
    { taal: "werpen/gooien (past participle)", nl: "thrown" },
    { taal: "begrijpen/verstaan (infinitive)", nl: "to understand" },
    { taal: "begrijpen/verstaan (past simple)", nl: "understood" },
    { taal: "begrijpen/verstaan (past participle)", nl: "understood" },
    { taal: "wakker worden/maken (infinitive)", nl: "to wake" },
    { taal: "wakker worden/maken (past simple)", nl: "woke" },
    { taal: "wakker worden/maken (past participle)", nl: "woken" },
    { taal: "dragen (van kleding) (infinitive)", nl: "to wear" },
    { taal: "dragen (van kleding) (past simple)", nl: "wore" },
    { taal: "dragen (van kleding) (past participle)", nl: "worn" },
    { taal: "winnen (infinitive)", nl: "to win" },
    { taal: "winnen (past simple)", nl: "won" },
    { taal: "winnen (past participle)", nl: "won" },
    { taal: "schrijven (infinitive)", nl: "to write" },
    { taal: "schrijven (past simple)", nl: "wrote" },
    { taal: "schrijven (past participle)", nl: "written" },
  ]
},
du_5000: {
  title: "Frans - 1-5000",
  words: [
    { taal: "5", nl: "fünf" },
    { taal: "27", nl: "siebenundzwanzig" },
    { taal: "54", nl: "vierundfünfzig" },
    { taal: "59", nl: "neunundfünfzig" },
    { taal: "95", nl: "fünfundneunzig" },
    { taal: "160", nl: "einhundertsechzig" },
    { taal: "173", nl: "einhundertdreiundsiebzig" },
    { taal: "205", nl: "zweihundertfünf" },
    { taal: "218", nl: "zweihundertachtzehn" },
    { taal: "245", nl: "zweihundertfünfundvierzig" },
    { taal: "258", nl: "zweihundertachtundfünfzig" },
    { taal: "261", nl: "zweihunderteinundsechzig" },
    { taal: "263", nl: "zweihundertdreiundsechzig" },
    { taal: "356", nl: "dreihundertsechsundfünfzig" },
    { taal: "376", nl: "dreihundertsechsundsiebzig" },
    { taal: "386", nl: "dreihundertsechsundachtzig" },
    { taal: "459", nl: "vierhundertneunundfünfzig" },
    { taal: "475", nl: "vierhundertfünfundsiebzig" },
    { taal: "483", nl: "vierhundertdreiundachtzig" },
    { taal: "521", nl: "fünfhunderteinundzwanzig" },
    { taal: "525", nl: "fünfhundertfünfundzwanzig" },
    { taal: "543", nl: "fünfhundertdreiundvierzig" },
    { taal: "553", nl: "fünfhundertdreiundfünfzig" },
    { taal: "567", nl: "fünfhundertsiebenundsechzig" },
    { taal: "570", nl: "fünfhundertsiebzig" },
    { taal: "582", nl: "fünfhundertzweiundachtzig" },
    { taal: "585", nl: "fünfhundertfünfundachtzig" },
    { taal: "646", nl: "sechshundertsechsundvierzig" },
    { taal: "654", nl: "sechshundertvierundfünfzig" },
    { taal: "702", nl: "siebenhundertzwei" },
    { taal: "713", nl: "siebenhundertdreizehn" },
    { taal: "745", nl: "siebenhundertfünfundvierzig" },
    { taal: "760", nl: "siebenhundertsechzig" },
    { taal: "768", nl: "siebenhundertachtundsechzig" },
    { taal: "793", nl: "siebenhundertdreiundneunzig" },
    { taal: "828", nl: "achthundertachtundzwanzig" },
    { taal: "838", nl: "achthundertachtunddreißig" },
    { taal: "840", nl: "achthundertvierzig" },
    { taal: "872", nl: "achthundertzweiundsiebzig" },
    { taal: "899", nl: "achthundertneunundneunzig" },
    { taal: "913", nl: "neunhundertdreizehn" },
    { taal: "914", nl: "neunhundertvierzehn" },
    { taal: "917", nl: "neunhundertsiebzehn" },
    { taal: "939", nl: "neunhundertneununddreißig" },
    { taal: "992", nl: "neunhundertzweiundneunzig" },
    { taal: "1023", nl: "eintausenddreiundzwanzig" },
    { taal: "1031", nl: "eintausendeinunddreißig" },
    { taal: "1052", nl: "eintausendzweiundfünfzig" },
    { taal: "1134", nl: "eintausendeinhundertvierunddreißig" },
    { taal: "1144", nl: "eintausendeinhundertvierundvierzig" },
    { taal: "1171", nl: "eintausendeinhunderteinundsiebzig" },
    { taal: "1253", nl: "eintausendzweihundertdreiundfünfzig" },
    { taal: "1274", nl: "eintausendzweihundertvierundsiebzig" },
    { taal: "1296", nl: "eintausendzweihundertsechsundneunzig" },
    { taal: "1308", nl: "eintausenddreihundertacht" },
    { taal: "1311", nl: "eintausenddreihundertelf" },
    { taal: "1324", nl: "eintausenddreihundertvierundzwanzig" },
    { taal: "1333", nl: "eintausenddreihundertdreiunddreißig" },
    { taal: "1339", nl: "eintausenddreihundertneununddreißig" },
    { taal: "1353", nl: "eintausenddreihundertdreiundfünfzig" },
    { taal: "1402", nl: "eintausendvierhundertzwei" },
    { taal: "1464", nl: "eintausendvierhundertvierundsechzig" },
    { taal: "1576", nl: "eintausendfünfhundertsechsundsiebzig" },
    { taal: "1629", nl: "eintausendsechshundertneunundzwanzig" },
    { taal: "1630", nl: "eintausendsechshundertdreißig" },
    { taal: "1648", nl: "eintausendsechshundertachtundvierzig" },
    { taal: "1717", nl: "eintausendsiebenhundertsiebzehn" },
    { taal: "1729", nl: "eintausendsiebenhundertneunundzwanzig" },
    { taal: "1736", nl: "eintausendsiebenhundertsechsunddreißig" },
    { taal: "1742", nl: "eintausendsiebenhundertzweiundvierzig" },
    { taal: "1764", nl: "eintausendsiebenhundertvierundsechzig" },
    { taal: "1792", nl: "eintausendsiebenhundertzweiundneunzig" },
    { taal: "1797", nl: "eintausendsiebenhundertsiebenundneunzig" },
    { taal: "1800", nl: "eintausendachthundert" },
    { taal: "1805", nl: "eintausendachthundertfünf" },
    { taal: "1806", nl: "eintausendachthundertsechs" },
    { taal: "1829", nl: "eintausendachthundertneunundzwanzig" },
    { taal: "1841", nl: "eintausendachthunderteinundvierzig" },
    { taal: "1867", nl: "eintausendachthundertsiebenundsechzig" },
    { taal: "1876", nl: "eintausendachthundertsechsundsiebzig" },
    { taal: "1877", nl: "eintausendachthundertsiebenundsiebzig" },
    { taal: "1886", nl: "eintausendachthundertsechsundachtzig" },
    { taal: "1906", nl: "eintausendneunhundertsechs" },
    { taal: "1908", nl: "eintausendneunhundertacht" },
    { taal: "1962", nl: "eintausendneunhundertzweiundsechzig" },
    { taal: "1974", nl: "eintausendneunhundertvierundsiebzig" },
    { taal: "2006", nl: "zweitausendsechs" },
    { taal: "2007", nl: "zweitausendsieben" },
    { taal: "2021", nl: "zweitausendeinundzwanzig" },
    { taal: "2031", nl: "zweitausendeinunddreißig" },
    { taal: "2060", nl: "zweitausendsechzig" },
    { taal: "2153", nl: "zweitausendeinhundertdreiundfünfzig" },
    { taal: "2158", nl: "zweitausendeinhundertachtundfünfzig" },
    { taal: "2167", nl: "zweitausendeinhundertsiebenundsechzig" },
    { taal: "2170", nl: "zweitausendeinhundertsiebzig" },
    { taal: "2172", nl: "zweitausendeinhundertzweiundsiebzig" },
    { taal: "2186", nl: "zweitausendeinhundertsechsundachtzig" },
    { taal: "2188", nl: "zweitausendeinhundertachtundachtzig" },
    { taal: "2194", nl: "zweitausendeinhundertvierundneunzig" },
    { taal: "2212", nl: "zweitausendzweihundertzwölf" },
    { taal: "2254", nl: "zweitausendzweihundertvierundfünfzig" },
    { taal: "2277", nl: "zweitausendzweihundertsiebenundsiebzig" },
    { taal: "2278", nl: "zweitausendzweihundertachtundsiebzig" },
    { taal: "2279", nl: "zweitausendzweihundertneunundsiebzig" },
    { taal: "2371", nl: "zweitausenddreihunderteinundsiebzig" },
    { taal: "2402", nl: "zweitausendvierhundertzwei" },
    { taal: "2405", nl: "zweitausendvierhundertfünf" },
    { taal: "2445", nl: "zweitausendvierhundertfünfundvierzig" },
    { taal: "2520", nl: "zweitausendfünfhundertzwanzig" },
    { taal: "2554", nl: "zweitausendfünfhundertvierundfünfzig" },
    { taal: "2578", nl: "zweitausendfünfhundertachtundsiebzig" },
    { taal: "2585", nl: "zweitausendfünfhundertfünfundachtzig" },
    { taal: "2656", nl: "zweitausendsechshundertsechsundfünfzig" },
    { taal: "2657", nl: "zweitausendsechshundertsiebenundfünfzig" },
    { taal: "2758", nl: "zweitausendsiebenhundertachtundfünfzig" },
    { taal: "2770", nl: "zweitausendsiebenhundertsiebzig" },
    { taal: "2787", nl: "zweitausendsiebenhundertsiebenundachtzig" },
    { taal: "2788", nl: "zweitausendsiebenhundertachtundachtzig" },
    { taal: "2818", nl: "zweitausendachthundertachtzehn" },
    { taal: "2911", nl: "zweitausendneunhundertelf" },
    { taal: "2941", nl: "zweitausendneunhunderteinundvierzig" },
    { taal: "2963", nl: "zweitausendneunhundertdreiundsechzig" },
    { taal: "2966", nl: "zweitausendneunhundertsechsundsechzig" },
    { taal: "2974", nl: "zweitausendneunhundertvierundsiebzig" },
    { taal: "2989", nl: "zweitausendneunhundertneunundachtzig" },
    { taal: "3033", nl: "dreitausenddreiunddreißig" },
    { taal: "3060", nl: "dreitausendsechzig" },
    { taal: "3064", nl: "dreitausendvierundsechzig" },
    { taal: "3101", nl: "dreitausendeinhunderteins" },
    { taal: "3109", nl: "dreitausendeinhundertneun" },
    { taal: "3113", nl: "dreitausendeinhundertdreizehn" },
    { taal: "3114", nl: "dreitausendeinhundertvierzehn" },
    { taal: "3127", nl: "dreitausendeinhundertsiebenundzwanzig" },
    { taal: "3153", nl: "dreitausendeinhundertdreiundfünfzig" },
    { taal: "3242", nl: "dreitausendzweihundertzweiundvierzig" },
    { taal: "3269", nl: "dreitausendzweihundertneunundsechzig" },
    { taal: "3272", nl: "dreitausendzweihundertzweiundsiebzig" },
    { taal: "3287", nl: "dreitausendzweihundertsiebenundachtzig" },
    { taal: "3437", nl: "dreitausendvierhundertsiebenunddreißig" },
    { taal: "3457", nl: "dreitausendvierhundertsiebenundfünfzig" },
    { taal: "3459", nl: "dreitausendvierhundertneunundfünfzig" },
    { taal: "3463", nl: "dreitausendvierhundertdreiundsechzig" },
    { taal: "3467", nl: "dreitausendvierhundertsiebenundsechzig" },
    { taal: "3510", nl: "dreitausendfünfhundertzehn" },
    { taal: "3562", nl: "dreitausendfünfhundertzweiundsechzig" },
    { taal: "3589", nl: "dreitausendfünfhundertneunundachtzig" },
    { taal: "3680", nl: "dreitausendsechshundertachtzig" },
    { taal: "3699", nl: "dreitausendsechshundertneunundneunzig" },
    { taal: "3715", nl: "dreitausendsiebenhundertfünfzehn" },
    { taal: "3717", nl: "dreitausendsiebenhundertsiebzehn" },
    { taal: "3759", nl: "dreitausendsiebenhundertneunundfünfzig" },
    { taal: "3764", nl: "dreitausendsiebenhundertvierundsechzig" },
    { taal: "3787", nl: "dreitausendsiebenhundertsiebenundachtzig" },
    { taal: "3835", nl: "dreitausendachthundertfünfunddreißig" },
    { taal: "3894", nl: "dreitausendachthundertvierundneunzig" },
    { taal: "3982", nl: "dreitausendneunhundertzweiundachtzig" },
    { taal: "4003", nl: "viertausenddrei" },
    { taal: "4043", nl: "viertausenddreiundvierzig" },
    { taal: "4090", nl: "viertausendneunzig" },
    { taal: "4101", nl: "viertausendeinhunderteins" },
    { taal: "4140", nl: "viertausendeinhundertvierzig" },
    { taal: "4159", nl: "viertausendeinhundertneunundfünfzig" },
    { taal: "4175", nl: "viertausendeinhundertfünfundsiebzig" },
    { taal: "4240", nl: "viertausendzweihundertvierzig" },
    { taal: "4323", nl: "viertausenddreihundertdreiundzwanzig" },
    { taal: "4335", nl: "viertausenddreihundertfünfunddreißig" },
    { taal: "4345", nl: "viertausenddreihundertfünfundvierzig" },
    { taal: "4364", nl: "viertausenddreihundertvierundsechzig" },
    { taal: "4376", nl: "viertausenddreihundertsechsundsiebzig" },
    { taal: "4393", nl: "viertausenddreihundertdreiundneunzig" },
    { taal: "4399", nl: "viertausenddreihundertneunundneunzig" },
    { taal: "4416", nl: "viertausendvierhundertsechzehn" },
    { taal: "4418", nl: "viertausendvierhundertachtzehn" },
    { taal: "4419", nl: "viertausendvierhundertneunzehn" },
    { taal: "4465", nl: "viertausendvierhundertfünfundsechzig" },
    { taal: "4468", nl: "viertausendvierhundertachtundsechzig" },
    { taal: "4504", nl: "viertausendfünfhundertvier" },
    { taal: "4523", nl: "viertausendfünfhundertdreiundzwanzig" },
    { taal: "4533", nl: "viertausendfünfhundertdreiunddreißig" },
    { taal: "4538", nl: "viertausendfünfhundertachtunddreißig" },
    { taal: "4563", nl: "viertausendfünfhundertdreiundsechzig" },
    { taal: "4598", nl: "viertausendfünfhundertachtundneunzig" },
    { taal: "4599", nl: "viertausendfünfhundertneunundneunzig" },
    { taal: "4647", nl: "viertausendsechshundertsiebenundvierzig" },
    { taal: "4648", nl: "viertausendsechshundertachtundvierzig" },
    { taal: "4730", nl: "viertausendsiebenhundertdreißig" },
    { taal: "4781", nl: "viertausendsiebenhunderteinundachtzig" },
    { taal: "4789", nl: "viertausendsiebenhundertneunundachtzig" },
    { taal: "4820", nl: "viertausendachthundertzwanzig" },
    { taal: "4821", nl: "viertausendachthunderteinundzwanzig" },
    { taal: "4828", nl: "viertausendachthundertachtundzwanzig" },
    { taal: "4838", nl: "viertausendachthundertachtunddreißig" },
    { taal: "4882", nl: "viertausendachthundertzweiundachtzig" },
    { taal: "4886", nl: "viertausendachthundertsechsundachtzig" },
    { taal: "4907", nl: "viertausendneunhundertsieben" },
    { taal: "4932", nl: "viertausendneunhundertzweiunddreißig" },
    { taal: "4946", nl: "viertausendneunhundertsechsundvierzig" },
    { taal: "4970", nl: "viertausendneunhundertsiebzig" },
    { taal: "4989", nl: "viertausendneunhundertneunundachtzig" },
    { taal: "4991", nl: "viertausendneunhunderteinundneunzig" },
  ]
},
du_vraagwrd: {
  title: "Frans - Vraagwrd",
  words: [
    { taal: "wanneer", nl: "wann" },
    { taal: "waarom", nl: "warum" },
    { taal: "wat", nl: "was" },
    { taal: "welk / welke", nl: "welch-" },
    { taal: "wie", nl: "wer" },
    { taal: "hoe", nl: "wie" },
    { taal: "waar", nl: "wo" },
    { taal: "waarvandaan", nl: "woher" },
    { taal: "waarnaartoe", nl: "wohin" },
  ]
},
du_woordlijst_a_blz43: {
  title: "Frans - Woordlijst",
  words: [
    { taal: "de letter, de letters", nl: "der Buchstabe, die Buchstaben" },
    { taal: "de zin, de zinnen", nl: "der Satz, die Sätze" },
    { taal: "het antwoord, de antwoorden", nl: "die Antwort, die Antworten" },
    { taal: "de vraag, de vragen", nl: "die Frage, die Fragen" },
    { taal: "het woord, de woorden", nl: "das Wort, die Wörter" },
    { taal: "Nederland", nl: "die Niederlande" },
    { taal: "Duitsland", nl: "Deutschland" },
    { taal: "(geen) idee", nl: "(keine) Ahnung" },
    { taal: "aanvinken", nl: "ankreuzen" },
    { taal: "werken", nl: "arbeiten" },
    { taal: "beantwoorden", nl: "beantworten" },
    { taal: "betekenen", nl: "bedeuten" },
    { taal: "eerste / laatste", nl: "erste – letzte" },
    { taal: "vragen", nl: "fragen" },
    { taal: "goed / beter / het best", nl: "gut – besser – am besten" },
    { taal: "horen, luisteren", nl: "hören" },
    { taal: "lezen", nl: "lesen" },
    { taal: "maken", nl: "machen" },
    { taal: "zeggen", nl: "sagen" },
    { taal: "mooi / mooier / het mooist", nl: "schön – schöner – am schönsten" },
    { taal: "schrijven", nl: "schreiben" },
    { taal: "vertalen", nl: "übersetzen" },
    { taal: "onderstrepen", nl: "unterstreichen" },
    { taal: "Veel plezier!", nl: "Viel Spaß!" },
  ]
},
du_woordlijst_b_blz43: {
  title: "Frans - Woordlijst",
  words: [
    { taal: "het uitstapje", nl: "der Ausflug" },
    { taal: "de leerling, de leerlingen", nl: "der Schüler, die Schüler" },
    { taal: "de trein", nl: "der Zug" },
    { taal: "de leerlinge", nl: "die Schülerin" },
    { taal: "de brugklas, 1e klas", nl: "die 7. Klasse" },
    { taal: "de deelstaat", nl: "das Bundesland" },
    { taal: "de fiets", nl: "das Fahrrad" },
    { taal: "de bioscoop", nl: "das Kino" },
    { taal: "de vakantie", nl: "die Ferien" },
    { taal: "de jongeren", nl: "die Jugendlichen" },
    { taal: "maar", nl: "aber" },
    { taal: "ook", nl: "auch" },
    { taal: "krijgen", nl: "bekommen" },
    { taal: "gebruiken", nl: "benutzen" },
    { taal: "nodig hebben", nl: "brauchen" },
    { taal: "ontdekken", nl: "entdecken" },
    { taal: "er is, er zijn", nl: "es gibt" },
    { taal: "rijden", nl: "fahren" },
    { taal: "komen / gaan", nl: "kommen / gehen" },
    { taal: "zin hebben in", nl: "Lust haben auf" },
    { taal: "niet", nl: "nicht" },
    { taal: "of", nl: "oder" },
    { taal: "en", nl: "und" },
    { taal: "veel / weinig", nl: "viel / wenig" },
  ]
},
};