name: Update version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create update.js
        run: |
          DATE=$(date -u +"%-d.%-m.%y")
          VERSION=$(git rev-list --count HEAD)
          echo "const update = \"$DATE.v$VERSION\";" > Update.js

      - name: Save update.js
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Update.js
          git diff --cached --quiet || git commit -m "Update version"
          git push